### ISSUE TITLE
为啥JustLoginRegisterTest这个demo登录时输入错误的密码也可以登录成功，是没有成功连接数据库吗

### ISSUE THREAD

**Issue by 123hj** [littlecurl/AppProjects#1]

**Comment by littlecurl** [comment]
> _No description provided._
不会呀，我这里的代码跑起来密码错误的话时不让登录成功的。你可以看看源码，我有进行match匹配。

**Comment by qinlinmo** [comment]
这个不做注册的话，怎么修改数据库的数据？就是类似于后台人员那种可以直接查看和修改数据库的数据那样？？？

**Comment by littlecurl** [comment]
直接查看的话，我另一篇博客有讲到，就是导出数据文件，然后用SQLite工具查看；要想修改数据，那就是后台调用update语句更新数据库了。

**Comment by vencieo** [comment]
我在您的基础下进行了修改，为什么我按注册就闪退，能否帮我解决一下？

**Comment by littlecurl** [comment]
把你修改后的源码发我一份，邮箱也行，或者我QQ:424171723------------------ 原始邮件 ------------------
发件人: "vencieo"<notifications@github.com>
发送时间: 2019年5月29日(星期三) 凌晨0:44
收件人: "littlecurl/AppProjects"<AppProjects@noreply.github.com>;
抄送: "LittleCurl"<littlecurl@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [littlecurl/AppProjects] 为啥JustLoginRegisterTest这个demo登录时输入错误的密码也可以登录成功，是没有成功连接数据库吗 (#1)



我在您的基础下进行了修改，为什么我按注册就闪退，能否帮我解决一下？
 
&mdash;

**Comment by DH-cmd** [comment]
请问这个可以实现登陆或者注册过后把用户名那些值传到另外的界面吗

**Comment by littlecurl** [comment]
首先回答主题，密码错误的话，应该是不能登陆成功的，你可以看我源码里的验证方法，我有调用数据库的查询方法和验证方法。 然后回答如何把登录后的数据传递给其他Activity，这个是Android入门的基本用法《第一行代码》2.3节有讲到，你也可以百度一下“使用intent在活动之间穿梭”，希望你能够理解。 ------------------ 原始邮件 ------------------
发件人: "DH-cmd"<notifications@github.com>
发送时间: 2019年6月15日(星期六) 晚上10:10
收件人: "littlecurl/AppProjects"<AppProjects@noreply.github.com>;
抄送: "LittleCurl"<littlecurl@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [littlecurl/AppProjects] 为啥JustLoginRegisterTest这个demo登录时输入错误的密码也可以登录成功，是没有成功连接数据库吗 (#1)



请问这个可以实现登陆或者注册过后把用户名那些值传到另外的界面吗
 
&mdash;
